### ISSUE TITLE
Comparison with higher-order sh

### ISSUE THREAD

**Issue by a1600012888** [ingra14m/Specular-Gaussians#11]
Thanks for your great work. 
Just our of curiosity, do you have comparisons with GaussianSplatting with 4-order or 5-order sh?

**Comment by ingra14m** [comment]
Really good question. I compared the higher order SH in vanilla GS in the latest version (it has not been updated on arxiv yet.). You can see the following figure.

<img width="1608" alt="image" src="https://github.com/user-attachments/assets/64c47aa9-5b2b-4faf-a96a-6cf18342570e">

According to my experiments, even 6-order SH cannot model the sharp specular highlights. I think this problem stems from the poor fitting capability of low-order SH. Maybe? I think 40-50 orders SH will make a difference? But the computational overhead is toooo much.

**Comment by a1600012888** [comment]
Thanks!
