### ISSUE TITLE
How can I render a transparent image using accumulation?

### ISSUE THREAD

**Issue by Learningm** [ingra14m/Specular-Gaussians#3]
I saw the 'sigma' related code part has been changed to 'depth' part.
https://github.com/ingra14m/Specular-Gaussians/blob/main/gaussian_renderer/__init__.py#L107

I used to render the foreground image into an RGBA image using the 'result[acc]'.
In this repo, how can I do this? Thanks.

**Comment by ingra14m** [comment]
You can refer to the [alpha branch](https://github.com/ingra14m/depth-diff-gaussian-rasterization/tree/alpha). It only has the forward pass. If you also want a backward pass for both depth and alpha, you can refer to [https://github.com/ashawkey/diff-gaussian-rasterization](https://github.com/ashawkey/diff-gaussian-rasterization)

**Comment by Learningm** [comment]
Got it, Thanks！
